logging:
  level:
    ROOT: INFO

spring:
  application.name: book-service

  banner:
    location: classpath:banner.txt

  datasource:
    platform: postgres
    url: jdbc:postgresql://postgresql:5432/db
    username: dbuser
    password: password

  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
      hbm2ddl:
        auto: create

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3

application:
  rememberKey: "RememberMeApplicationKey"
  locale: "ru_RU"
  strength: 4
