logging:
  level:
    ROOT: DEBUG

spring:
  banner:
    location: classpath:banner.txt
  data:
    mongodb:
      host: localhost
      port: 27017
      database: booksdb

application:
  locale: "ru_RU"
